### ISSUE TITLE
Long title

### ISSUE THREAD

**Issue by taxipomme** [backtracking/bibtex2html#12]
It seems that too long titles (more than 64 characters, say) break accent translation.

For instance
title="Du Th{\'e}or{\`e}me de {R}amsey {\`a} la Conjecture d'{E}rd{\H o}s--{H}ajnal"
-> Du th&eacute;or&egrave;me de Ramsey &agrave; la conjecture d'Erd
  os&ndash;Hajnal

but title="Du Th{\'e}or{\`e}me de {R}amsey {\`a} la d'{E}rd{\H o}s--{H}ajnal"
-> Du th&eacute;or&egrave;me de Ramsey &agrave; la d'Erd&#337;s&ndash;Hajnal

**Comment by backtracking** [comment]
Thanks for reporting this bug. It is fixed in commit c2a44934e.
(This was indeed related to long BibTeX fields: when translated to pure LaTeX, newlines were inserted and not correctly ignored when parsing LaTeX macros in the HTML translation.)
