### ISSUE TITLE
no links generated in _bib.html for https URLs

### ISSUE THREAD

**Issue by walter-guttmann** [backtracking/bibtex2html#15]
If the url field of a BibTeX entry contains a URL that starts with https (instead of http) no link is generated in the _bib.html file. This seems to happen because the url_re regular expression in biboutput.ml line 30 does not match strings with https. Perhaps https could be added to url_re.

**Comment by k4rtik** [comment]
I am not seeing this issue, I have lots of URLs starting with https. Perhaps fixed since the previous comment?

**Comment by walter-guttmann** [comment]
The issue is still there. If z.bib contains an entry whose url field starts with https://, it is processed and z.html will contain a link, but z_bib.html will only contain the text of the url without a link. In contrast, if the url field starts with http://, also z_bib.html will contain a link. (The url_re regular expression in biboutput.ml line 30 still does not match https.)

**Comment by dClauzel** [comment]
biboutput.ml line:30 `let url_re = Str.regexp "\\(ftp\\|http\\)://.*"`

This cannot match `https://` URLs.

**Comment by backtracking** [comment]
This is now fixed. Apologies for having neglected this issue for so long.

**Comment by k4rtik** [comment]
Thanks, I went ahead and made this git repo to be [available through homebrew](https://github.com/Homebrew/homebrew-core/commit/a66ad3db4ba2bce08c8418a676374572f68f1357) so that these changes are widely available. Just need to issue `brew install --HEAD bibtex2html` from now on.
