### ISSUE TITLE
Group entries by year

### ISSUE THREAD

**Issue by khatchad** [backtracking/bibtex2html#2]
Is it possible to group bib entries by year?

**Comment by backtracking** [comment]
Hi,

Not directly, but here are two solutions:

- use a custom BibTeX style (.bst file) that does such a grouping

- first use bib2bib to extract BibTeX entries for a given year, then use
bibtex2html to translate the result to HTML (bib2bib comes with
bibtex2html). We use such a combination to build the publication pages
of our team: http://toccata.lri.fr/biblio.en.shtml

Hope this helps,
--
Jean-Christophe

**Comment by khatchad** [comment]
Ah cool. Thanks! It would also be great to have a command line option for this but unfortunately I don't know much about ML :).
