### ISSUE TITLE
Unknown macro: \setminus

### ISSUE THREAD

**Issue by MLopez-Ibanez** [backtracking/bibtex2html#29]
`$A \setminus B$` is translated to `<em>A</em> <em>B</em>`. The workaround:
```latex
\newcommand{\setminus}{&setminus;}
```
doesn't work because it becomes `<em>A</em> &<em>setminus</em>;<em>B</em>`. But

```latex
\newcommand{\setminus}{ &#8726; }
```
does work.

**Comment by backtracking** [comment]
The master version of bibtex2html already has a translation for \setminus (commit b582381c from last October).
It is translated to &#x29f5; (a backslash).

If you cannot use the master version, here is another workaround:
```\newcommand{\setminus}{\backslash}```
(put that in some `macros.tex` file and run `bibtex2html -m macros.tex file.bib`)

**Comment by MLopez-Ibanez** [comment]
Great! thanks!
