### ISSUE TITLE
utf8?

### ISSUE THREAD

**Issue by eroux** [backtracking/bibtex2html#3]
Hello,

Is it possible to generate html from utf8 input? I'm using chinese characters (not fitting into 8-bit encodings)...

Thank you,

**Comment by backtracking** [comment]
Hi,

Yes, a BibTeX file containing utf-8 characters is fine and will result
into a HTML output containing these characters. (I just made a test.)
bibtex2html, as bibtex, is rather agnostic wrt to character encoding.

Best regards,
--
Jean-Christophe

**Comment by eroux** [comment]
Indeed,, sorry, I don't know what I've been doing wrong in my tests...
