### ISSUE TITLE
Unknown macro: \rangle

### ISSUE THREAD

**Issue by k4rtik** [backtracking/bibtex2html#33]
For bibtex fields containing `$\rangle$` such as
```
title         = {t$|$ket$\rangle$: a retargetable compiler for {NISQ} devices},
[...]
title         = {{{LIQ}}$Ui|\rangle$: {{A Software Design Architecture}} and {{Domain}}-{{Specific Language}} for {{Quantum Computing}}},
```

I am getting this error: `Unknown macro: \rangle` while this macro seems defined in two places in `latexmacros.ml`: https://github.com/backtracking/bibtex2html/search?q=rangle&type=code

**Comment by backtracking** [comment]
For such a macro to be translated, you must use either `-unicode`  or `-html-entities` on the command line.
Both should work fine with macro `\rangle` (I just checked).
My apologies if this is not/badly documented.

**Comment by k4rtik** [comment]
Ah, thanks, I was not aware of that.
