### ISSUE TITLE
bibtex: Not writing to /tmp/bib2html*.blg (openout_any = p) on newer texlive installations

### ISSUE THREAD

**Issue by kevinstadler** [backtracking/bibtex2html#9]
On my new Fedora 25 installation bibtex2html (v1.97) fails to execute with the following error (twice per invocation, actually):

```
calling BibTeX...
bibtex: Not writing to /tmp/bib2html3d1304.blg (openout_any = p).
I couldn't open file name `/tmp/bib2html3d1304.blg'
error 1 while running bibtex
```

In the `/tmp` directory one can see that only the respective .aux files were created, but newer default configurations of BibTeX appear to refuse writing to files outside the current working directory (it's not related to the version of BibTeX itself, my old installation which worked out of the box was a TeX Live 2013/Debian build of BibTeX 0.99d, the new one where I encountered the problem is a new 2016 build installation, also of 0.99d).

Workaround: one can change the write restriction (globally) by finding the local `texmf.cnf` file (mine was in `/usr/share/texlive/texmf-dist/web2c/`, elsewhere I read `/usr/share/texlive/texmf/web2c/`) and changing the `openout_any` setting to either `r` or `a` (just away from `p`). This works for now, but it would probably be preferrable to leave that setting as it is and simply have bib2html create the temp files in the directory where it is invoked (the temp file names already have random bits in them so that shouldn't be a problem?)

Thanks for bib2html! :)

**Comment by backtracking** [comment]
Dear Kevin,

This is a known issue. It is fixed as you are suggesting (i.e. by
writing temporary files in the current directory instead) in version
1.98 of bibtex2html.

As explained on bibtex2html's web site (
https://www.lri.fr/~filliatr/bibtex2html/ ) a workaround for versions up
to 1.97 is to tell your system to use another directory for temporary
files, such as the current directory (as you are suggesting). You can do
that by running this shell command prior to the invocation of bibtex2html:

  export TMPDIR=.

(for instance in a script or Makefile of yours that is calling bibtex2html).

Hope this helps,
--
Jean-Christophe

**Comment by kevinstadler** [comment]
My apologies, the bibtex2html website didn't come up when I googled for the error and on github I merely looked for it in the issues (didn't realise it's already been affecting other Texlive installations for so long!)
